knp_snappy:
    pdf:
        enabled:    true
        binary:     "C:\\Users\\21653\\Downloads\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"
        options:    []
    image:
        enabled:    true
        binary:     "C:\\Users\\21653\\Downloads\\wkhtmltopdf\\bin\\wkhtmltoimage.exe"
        options:    
                  
               enable-local-file-access: true
