framework:
    rate_limiter:
        password_reset:
            policy: 'sliding_window'
            limit: 3
            interval: '1 minute'
        anonymous_api:
            policy: 'fixed_window'
            limit: 30
            interval: '1 minute'
