security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            
            # Enable Two-Factor Authentication
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check  # Simply enable 2FA for this firewall

            custom_authenticators:
                - App\Security\GoogleAuthenticator
            entry_point: App\Security\GoogleAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: username
                password_parameter: password
                default_target_path: app_home

            logout:
                path: app_logout
                target: app_login

    access_control:
        # Public routes
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/google-test$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }  # Adjusted role for 2FA process
        - { path: ^/password-reset, roles: PUBLIC_ACCESS }
        - { path: ^/terms, roles: PUBLIC_ACCESS }

        # Authenticated users routes
        - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/settings, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }

        # Route for users who need to update their profile
        - { path: ^/update-profile, roles: IS_AUTHENTICATED_FULLY }

        # Role-specific routes
        - { path: ^/terrain$, roles: [ROLE_AGRICULTURE, ROLE_ADMIN] }
        - { path: ^/listprod, roles: ROLE_CLIENT }
        - { path: ^/admin_recyclage_list, roles: ROLE_WORKER }

        # Catch-all requiring authentication
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    totp:
        enabled: true
        server_name: "Your Symfony App"
        template: 'two_factor_controller_php/2fa_verify.html.twig'  # Custom template for 2FA form
        # Define the form route and check route globally (optional, can be overridden per firewall)
        # auth_form_path: app_2fa  # Not needed here unless overriding defaults
        # check_path: app_2fa_check  # Not needed here unless overriding defaults