controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

generate_invoice_pdf:
  path: /commande/{commandeId}/facture
  controller: App\Controller\CommandesController::generateInvoicePdf

generate_invoice_pdf_admin:
  path: /commandeAdmin/{commandeId}/facture
  controller: App\Controller\CommandesController::generateInvoicePdfAdmin

request_password_reset:
  path: /password-reset
  controller: App\Controller\PasswordResetController::requestPasswordReset

verify_reset_code:
  path: /password-reset/verify
  controller: App\Controller\PasswordResetController::verifyResetCode

reset_password:
  path: /password-reset/reset
  controller: App\Controller\PasswordResetController::resetPassword
