# config/services.yaml

parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    imagess_directory: '%kernel.project_dir%/public/uploads/produits'
    # ... other parameters remain unchanged

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Add this service definition FIRST
    Endroid\QrCode\Builder\BuilderInterface:
        class: Endroid\QrCode\Builder\Builder

    # Then the rest of your services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Other service definitions remain unchanged...
    App\Service\MailerService:
        autowire: true

    App\EventSubscriber\CartSubscriber:
        tags: ['kernel.event_subscriber']

    App\Security\GoogleAuthenticator:
        arguments:
            $clientRegistry: '@knpu.oauth2.registry'
            $entityManager: '@doctrine.orm.entity_manager'
            $router: '@router'
            $userRepository: '@App\Repository\UserRepository'
            $logger: '@logger'
        tags: ['security.authenticator']

    App\Security\TotpAuthenticatorInterface:
        class: App\Security\TotpAuthenticator
        autowire: true