parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    imagess_directory: '%kernel.project_dir%/public/uploads/produits'
    imgs_directory: '%kernel.project_dir%/public/uploads/collecte'
    imgs_directory: '%kernel.project_dir%/public/uploads/collecte'
    image_directory: '%kernel.project_dir%/public/uploads/recyclage_img'
    images_directory: '%kernel.project_dir%/public/uploads/terrains'
    upload_directory: '%kernel.project_dir%/public/uploads'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
    Endroid\QrCode\Builder\BuilderInterface: ~
    unsplash_api_key: '%env(UNSPLASH_API_KEY)%'


services:
    # Default configuration for services in this file
    # Default configuration for services in this file
    _defaults:
        autowire: true  # Automatically injects dependencies in your services
        autowire: true  # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Register all controllers automatically

    # Register all controllers automatically
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    # Register all services, excluding specific directories
    
    # Register all services, excluding specific directories
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    # Explicitly register MailerService to ensure it's available
    App\Service\MailerService:
        autowire: true
        autoconfigure: true
        
    App\Service\CropPredictionService:
        arguments:
            $projectDir: '%kernel.project_dir%'
    # Explicitly register CartSubscriber
    
    # Explicitly register MailerService to ensure it's available
    App\Service\MailerService:
        autowire: true
        autoconfigure: true
        
    App\Service\CropPredictionService:
        arguments:
            $projectDir: '%kernel.project_dir%'
    # Explicitly register CartSubscriber
    App\EventSubscriber\CartSubscriber:
        tags: ['kernel.event_subscriber']
    App\Service\OpenAIService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'
    # Register GoogleAuthenticator service
    App\Security\GoogleAuthenticator:
        arguments:
            $clientRegistry: '@knpu.oauth2.registry'
            $entityManager: '@doctrine.orm.entity_manager'
            $router: '@router'
            $userRepository: '@App\Repository\UserRepository'
            $logger: '@logger'
        tags: ['security.authenticator']
    App\Service\UnsplashService:
        arguments:
            $apiKey: '%unsplash_api_key%'
