parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    imagess_directory: '%kernel.project_dir%/public/uploads/produits'
    imgs_directory: '%kernel.project_dir%/public/uploads/collecte' 
    image_directory: '%kernel.project_dir%/public/uploads/recyclage_img'
    images_directory: '%kernel.project_dir%/public/uploads/terrains'
    upload_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Register all controllers automatically
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Register all services, excluding specific directories
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicitly register MailerService to ensure it's available
    App\Service\MailerService:
        autowire: true
        autoconfigure: true

    # Explicitly register CartSubscriber
    App\EventSubscriber\CartSubscriber:
        tags: ['kernel.event_subscriber']
